/*
 * flutter_wwise — C shim over the Audiokinetic Wwise sound engine.
 *
 * Why this file exists
 * --------------------
 * Wwise's runtime API lives in C++ namespaces (AK::SoundEngine::PostEvent,
 * AK::SoundEngine::LoadBank, ...). dart:ffi can only bind flat C symbols, and
 * name-mangled C++ symbols are neither stable nor pleasant to bind.
 *
 * This header declares a small `extern "C"` surface that:
 *   - gives dart:ffi stable, unmangled symbols
 *   - keeps every Wwise-version-specific detail on the C++ side
 *   - maps Wwise's integer result codes into a small typed enum
 *
 * Ownership rules
 * ---------------
 *   - All `const char*` parameters are borrowed for the duration of the call
 *     only. The shim copies what it needs. Callers may free their buffers
 *     immediately after the call returns.
 *   - The string returned by hc_wwise_last_error() is owned by the shim and is
 *     valid until the next call on the same thread. Do not free it.
 */

#ifndef HC_WWISE_SHIM_H
#define HC_WWISE_SHIM_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bumped whenever this surface changes incompatibly. Dart checks it at load
 * time and fails fast with a clear message rather than crashing on a mismatched
 * call signature. */
#define HC_WWISE_SHIM_VERSION 1

/* Mirrors AK::AkGameObjectID without pulling in Wwise headers, so that Dart
 * codegen and the CI hygiene job never need the SDK present. */
typedef uint64_t hc_game_object_id;

/* Mirrors AK::AkUniqueID. */
typedef uint32_t hc_unique_id;

/* Result codes. Never expose raw AKRESULT values across the FFI boundary:
 * map them here so Dart can throw something meaningful. */
typedef enum hc_result {
  HC_OK = 0,

  /* Lifecycle */
  HC_ERR_ALREADY_INITIALIZED = 1,
  HC_ERR_NOT_INITIALIZED = 2,
  HC_ERR_INIT_FAILED = 3,

  /* Argument validation performed by the shim */
  HC_ERR_NULL_ARGUMENT = 10,
  HC_ERR_EMPTY_STRING = 11,

  /* Bank operations */
  HC_ERR_BANK_LOAD_FAILED = 20,
  HC_ERR_BANK_UNLOAD_FAILED = 21,
  HC_ERR_BANK_NOT_FOUND = 22,

  /* Game objects */
  HC_ERR_GAME_OBJECT_INVALID = 30,
  HC_ERR_GAME_OBJECT_REGISTER_FAILED = 31,

  /* Events, RTPC, switches and states */
  HC_ERR_EVENT_ID_NOT_FOUND = 40,
  HC_ERR_RTPC_NOT_FOUND = 41,

  /* Anything not yet mapped specifically. Kept distinct so callers can tell
   * "known failure" from "we have not seen this one yet". */
  HC_ERR_UNMAPPED = 90,
  HC_ERR_INTERNAL = 91
} hc_result;

/* ------------------------------------------------------------------ */
/* Lifecycle                                                          */
/* ------------------------------------------------------------------ */

/* Initialise the sound engine.
 *
 * init_bank_path  Path to your project's Init.bnk (portable, forward slashes
 *                 are fine on Windows too). Underscore-prefixed AK files such
 *                 as "Init.bnk" are generated by the Wwise authoring tool.
 * sample_rate     Engine sample rate. 0 means "use the platform default".
 *
 * Returns HC_ERR_ALREADY_INITIALIZED if called twice without an intervening
 * hc_wwise_term(). */
hc_result hc_wwise_init(const char* init_bank_path, uint32_t sample_rate);

/* Shut the engine down and release its resources. Safe to call when not
 * initialised (returns HC_OK). */
hc_result hc_wwise_term(void);

bool hc_wwise_is_initialized(void);

/* Advance the audio graph by one buffer.
 *
 * Wwise does not create its own audio thread when embedded this way; the host
 * drives it. Call this from the audio callback or from a paced timer, at a
 * cadence matching buffer_size in the engine's init settings. Calling it too
 * rarely produces dropouts; too often wastes CPU. */
hc_result hc_wwise_render_audio(void);

/* ------------------------------------------------------------------ */
/* SoundBanks                                                         */
/* ------------------------------------------------------------------ */

/* Load a SoundBank by name, e.g. "Main.bnk". Loads from memory if the bank was
 * previously registered with hc_wwise_register_bank_memory(). */
hc_result hc_wwise_load_bank(const char* bank_name);

hc_result hc_wwise_unload_bank(const char* bank_name);

/* Register a bank living in caller-owned memory (e.g. Flutter asset bytes
 * already loaded into a ByteData). The shim keeps the pointer; the buffer must
 * outlive the bank. Returns the bank id through out_bank_id when non-NULL.
 *
 * TODO(shim): implement; declared so the Dart side can be designed against it. */
hc_result hc_wwise_register_bank_memory(
    const char* bank_name,
    const void* data,
    uint32_t size,
    hc_unique_id* out_bank_id);

/* ------------------------------------------------------------------ */
/* Game objects                                                       */
/* ------------------------------------------------------------------ */

/* Register a game object and return its id.
 *
 * Wwise requires every sound to be attributed to a game object. For a UI-driven
 * app it is usually enough to register one per logical emitter (e.g. "ui",
 * "shaker", "ambience").
 *
 * Returns 0 (HC_INVALID_GAME_OBJECT) on failure; id 0 is never a valid object. */
hc_game_object_id hc_wwise_register_game_object(const char* name);

hc_result hc_wwise_unregister_game_object(hc_game_object_id id);

/* ------------------------------------------------------------------ */
/* Events                                                             */
/* ------------------------------------------------------------------ */

/* Post an Event by name, as defined in the Wwise authoring tool
 * (e.g. "Play_IceDrop"). Returns the playing id, or 0 on failure.
 *
 * Pass HC_INVALID_GAME_OBJECT for the game_object_id to let Wwise use the
 * default/global scope. */
hc_unique_id hc_wwise_post_event(const char* event_name,
                                 hc_game_object_id game_object_id);

/* ------------------------------------------------------------------ */
/* Real-time parameters                                               */
/* ------------------------------------------------------------------ */

/* Set a Game Parameter (RTPC) value in real time.
 *
 * This is the hook that makes interactive audio possible: e.g. feed a phone's
 * accelerometer magnitude into a "ShakeIntensity" RTPC so that how hard the
 * user shakes changes the sound, not just which sound plays.
 *
 * Set game_object_id to 0 to target the global scope. */
hc_result hc_wwise_set_rtpc(const char* rtpc_name, float value,
                            hc_game_object_id game_object_id);

/* ------------------------------------------------------------------ */
/* Diagnostics                                                        */
/* ------------------------------------------------------------------ */

/* Last human-readable error on this thread, or an empty string. Owned by the
 * shim; valid until the next shim call on the same thread. */
const char* hc_wwise_last_error(void);

/* Shim version, for a runtime compatibility check against
 * HC_WWISE_SHIM_VERSION. */
int hc_wwise_shim_version(void);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif /* HC_WWISE_SHIM_H */
